version: '3'

services:
  database:
    container_name: h2h-tech_database
    image: postgres:14
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres123
    ports:
      - 5432:5432
    networks:
      - postgres-db-network
    volumes:
      - ./data/database/data:/var/lib/postgresql/data
      - ./data/database/create-db.sql:/docker-entrypoint-initdb.d/create_database.sql

  pgadmin:
    image: dpage/pgadmin4
    container_name: h2h-tech_pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: teste@teste.com
      PGADMIN_DEFAULT_PASSWORD: teste
    ports:
      - 16543:80
    volumes:
      - ./data/pgadmin/data:/var/lib/pgadmin
    networks:
      - postgres-db-network

  php-fpm:
    container_name: h2h-tech_php-fpm
    build:
      context: ./php-fpm
    depends_on:
      - database
    environment:
      - APP_ENV=${APP_ENV}
      - APP_SECRET=${APP_SECRET}
      - DATABASE_URL=${DATABASE_URL}
    networks:
      - postgres-db-network
    volumes:
      - ./../src/:/var/www/html

  nginx:
    container_name: h2h-tech_nginx
    image: nginx:alpine
    volumes:
      - "./nginx/ssl:/etc/ssl"
      - "./nginx/default.conf:/etc/nginx/conf.d/default.conf"
      - "./nginx/default.template.conf:/etc/nginx/conf.d/default.template"
      - ./../src/:/var/www/html
      - ./logs:/var/log
    ports:
      - "8000:80"
      - "3000:443"
    environment:
      - NGINX_HOST=${NGINX_HOST}
    command: /bin/sh -c "envsubst '$$NGINX_HOST' < /etc/nginx/conf.d/default.template > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"  
    restart: always
    depends_on:
      - php-fpm
      - database
    networks:
      - postgres-db-network

# volumes:
#     postgres-db-volume:
#         driver: local
#         driver_opts:
#             type: none
#             o: bind
#             device: ./db-data
networks:
    postgres-db-network:
        driver: bridge
